
###
POST http://127.0.0.1:8000/auth/login
content-type: application/json

{
    "email": "hel2@gmail.com",
    "password": "12345678"
}
    

###
POST http://127.0.0.1:8000/auth/register
content-type: application/json

{
  "username": "hel2",
  "email": "hel2@gmail.com",
  "password": "12345678"
}

###
GET http://127.0.0.1:8000/products 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

